export const transtionsWeathers = {
  'thunderstorm with light rain': 'гроза с небольшим дождём',
  'thunderstorm with rain': 'гроза с дождём',
  'thunderstorm with heavy rain': 'гроза с сильным дождём',
  'light thunderstorm': 'лёгкая гроза',
  thunderstorm: 'гроза',
  'heavy thunderstorm': 'сильная гроза',
  'ragged thunderstorm': 'местами гроза',
  'thunderstorm with light drizzle': 'гроза с небольшой моросью',
  'thunderstorm with drizzle': 'гроза с моросью',
  'thunderstorm with heavy drizzle': 'гроза с сильной моросью',

  'light intensity drizzle': 'лёгкая морось',
  drizzle: 'морось',
  'heavy intensity drizzle': 'сильная морось',
  'light intensity drizzle rain': 'лёгкий моросящий дождь',
  'drizzle rain': 'моросящий дождь',
  'heavy intensity drizzle rain': 'сильный моросящий дождь',
  'shower rain and drizzle': 'ливень и морось',
  'heavy shower rain and drizzle': 'сильный ливень и морось',
  'shower drizzle': 'ливневая морось',

  'light rain': 'лёгкий дождь',
  'moderate rain': 'умеренный дождь',
  'heavy intensity rain': 'сильный дождь',
  'very heavy rain': 'очень сильный дождь',
  'extreme rain': 'экстремально сильный дождь',
  'freezing rain': 'ледяной дождь',
  'light intensity shower rain': 'лёгкий ливень',
  'shower rain': 'ливень',
  'heavy intensity shower rain': 'сильный ливень',
  'ragged shower rain': 'местами ливень',

  'light snow': 'лёгкий снег',
  snow: 'снег',
  'heavy snow': 'сильный снег',
  sleet: 'мокрый снег',
  'light shower sleet': 'лёгкий ливень с мокрым снегом',
  'shower sleet': 'ливень с мокрым снегом',
  'light rain and snow': 'лёгкий дождь и снег',
  'rain and snow': 'дождь и снег',
  'light shower snow': 'лёгкий ливневый снег',
  'shower snow': 'ливневый снег',
  'heavy shower snow': 'сильный ливневый снег',

  mist: 'дымка',
  smoke: 'дым',
  haze: 'мгла',
  'sand/dust whirls': 'песчаные/пылевые вихри',
  fog: 'туман',
  sand: 'песок',
  dust: 'пыль',
  'volcanic ash': 'вулканический пепел',
  squalls: 'шквалы',
  tornado: 'торнадо',

  'clear sky': 'ясно',

  'few clouds: 11-25%': 'малооблачно',
  'scattered clouds: 25-50%': 'переменная облачность',
  'broken clouds: 51-84%': 'облачно с прояснениями',
  'overcast clouds: 85-100%': 'пасмурно',
}
